apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-api-proxy-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-api-proxy-app
  template:
    metadata:
      labels:
        app: kubernetes-api-proxy-app
    spec:
      containers:
        - name: proxy-container
          command: ["/bin/sh"]
          args: ["-c", "apk add --update --no-cache socat;socat TCP-LISTEN:443,fork TCP:kubernetes.default.svc.cluster.local:443"]
          image: alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-proxy-service
  namespace: default
spec:
  selector:
    app: kubernetes-api-proxy-app
  ports:
    - name: k8s-api-proxy-app-port
      port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-api-proxy-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-api-proxy-sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubernetes-api-proxy-sa
    namespace: default
